_BASE_: Fast-COCO-InstanceSegmentation.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_vd_backbone"
  WEIGHTS: "checkpoints/resnet50d_ra2-464e36ba.pkl"
  RESNETS:
    DEFORM_ON_PER_STAGE: [ False, False, True, True ] # dcn on res4, res5
INPUT:
  MIN_SIZE_TEST: 576
  MAX_SIZE_TEST: 777
OUTPUT_DIR: "output/fastinst_r50-vd-dcn_ppm-fpn_bs16_50ep_x1_576"
